export const vocabularySets = [
  {
    title: "1A Grammar and Vocabulary",
    description: "Daily activities, routines, and lifestyle words",
    terms: [
      { term: "activity", definition: "etkinlik, faaliyet" },
      { term: "amazing", definition: "harika, şaşırtıcı" },
      { term: "before/after school", definition: "okuldan önce / okuldan sonra" },
      { term: "come from sth", definition: "bir şeyden gelmek/kaynaklanmak" },
      { term: "do exercise", definition: "egzersiz yapmak" },
      { term: "do homework", definition: "ödev yapmak" },
      { term: "do housework", definition: "ev işi yapmak" },
      { term: "extra lessons", definition: "ek dersler" },
      { term: "free time", definition: "boş zaman" },
      { term: "get dressed", definition: "giyinmek" },
      { term: "get home", definition: "eve varmak" },
      { term: "get up", definition: "kalkmak, uyanmak" },
      { term: "go home", definition: "eve gitmek" },
      { term: "go out with friends", definition: "arkadaşlarla dışarı çıkmak" },
      { term: "go shopping", definition: "alışverişe gitmek" },
      { term: "go to a club", definition: "kulübe gitmek" },
      { term: "go to bed", definition: "yatmak" },
      { term: "go to school/work", definition: "okula/işe gitmek" },
      { term: "have a shower", definition: "duş almak" },
      { term: "have breakfast/lunch/dinner", definition: "kahvaltı/öğle/akşam yemeği yemek" },
      { term: "have lessons", definition: "ders çalışmak/dersi olmak" },
      { term: "life", definition: "hayat, yaşam" },
      { term: "meal", definition: "öğün, yemek" },
      { term: "play chess", definition: "satranç oynamak" },
      { term: "routine", definition: "rutin" },
      { term: "schoolday", definition: "okul günü" },
      { term: "start", definition: "başlamak" },
      { term: "study", definition: "ders çalışmak" },
      { term: "unusual", definition: "olağandışı" },
      { term: "wear a uniform", definition: "üniforma giymek" },
      { term: "world", definition: "dünya" }
    ]
  },
  {
    title: "1B Vocabulary",
    description: "Hobbies, frequency, and leisure activities",
    terms: [
      { term: "every month", definition: "her ay" },
      { term: "go to a friend’s house", definition: "bir arkadaşın evine gitmek" },
      { term: "go to the cinema", definition: "sinemaya gitmek" },
      { term: "go to a party", definition: "bir partiye gitmek" },
      { term: "go to a concert", definition: "konsere gitmek" },
      { term: "hang out with friends", definition: "arkadaşlarla takılmak" },
      { term: "have a guitar lesson", definition: "gitar dersi almak" },
      { term: "late", definition: "geç, geç kalmış" },
      { term: "listen to music", definition: "müzik dinlemek" },
      { term: "once/twice/three times a week", definition: "haftada bir/iki/üç kez" },
      { term: "play computer games", definition: "bilgisayar oyunu oynamak" },
      { term: "play games on your mobile phone", definition: "cep telefonunda oyun oynamak" },
      { term: "play sport/tennis/football", definition: "spor/tenis/futbol oynamak" },
      { term: "read a book", definition: "kitap okumak" },
      { term: "spend", definition: "harcamak (zaman/para)" },
      { term: "watch TV/a film", definition: "TV/film izlemek" },
      { term: "write a blog", definition: "blog yazmak" }
    ]
  },
  {
    title: "1C Grammar",
    description: "Technology usage and habits",
    terms: [
      { term: "addict", definition: "bağımlı" },
      { term: "answer", definition: "cevap vermek" },
      { term: "check your phone", definition: "telefonunu kontrol etmek" },
      { term: "die", definition: "ölmek (şarj bitmesi)" },
      { term: "feel bad", definition: "kötü hissetmek" },
      { term: "feel nervous", definition: "gergin hissetmek" },
      { term: "get a signal", definition: "sinyal almak (telefon çekmesi)" },
      { term: "miss", definition: "özlemek / kaçırmak" },
      { term: "phone battery", definition: "telefon bataryası" },
      { term: "quiz", definition: "test, sınav" },
      { term: "sign", definition: "işaret, tabela" },
      { term: "sound", definition: "ses" },
      { term: "switch off", definition: "kapatmak (elektronik)" },
      { term: "take photos", definition: "fotoğraf çekmek" },
      { term: "text", definition: "mesaj yazmak" },
      { term: "true", definition: "doğru, gerçek" }
    ]
  },
  {
    title: "1D Reading and Vocabulary",
    description: "Interests, people, and culture",
    terms: [
      { term: "adult", definition: "yetişkin" },
      { term: "be interested in sth", definition: "bir şeye ilgi duymak" },
      { term: "be on the phone", definition: "telefonda olmak" },
      { term: "boring", definition: "sıkıcı" },
      { term: "care about sth", definition: "bir şeyi önemsemek" },
      { term: "celebrity", definition: "ünlü kişi" },
      { term: "clothes", definition: "kıyafetler" },
      { term: "cycle", definition: "bisiklet sürmek" },
      { term: "do sport", definition: "spor yapmak" },
      { term: "event", definition: "etkinlik, olay" },
      { term: "experience", definition: "deneyim, tecrübe" },
      { term: "forget", definition: "unutmak" },
      { term: "get back", definition: "geri dönmek" },
      { term: "have fun", definition: "eğlenmek" },
      { term: "hobby", definition: "hobi" },
      { term: "kind of music", definition: "müzik türü" },
      { term: "look up", definition: "araştırmak, yukarı bakmak" },
      { term: "make a decision", definition: "karar vermek" },
      { term: "modern", definition: "modern" },
      { term: "newspaper", definition: "gazete" },
      { term: "online", definition: "çevrimiçi" },
      { term: "put down", definition: "yere koymak" },
      { term: "put on (a song)", definition: "(şarkı) açmak/çalmak" },
      { term: "real world", definition: "gerçek dünya" },
      { term: "send a message", definition: "mesaj göndermek" },
      { term: "similar", definition: "benzer" },
      { term: "social network", definition: "sosyal ağ" },
      { term: "stay in", definition: "evde kalmak" },
      { term: "stereotype", definition: "basmakalıp yargı" },
      { term: "stuff", definition: "şeyler, eşyalar" },
      { term: "subject", definition: "konu, ders" },
      { term: "taste in music", definition: "müzik zevki" },
      { term: "team", definition: "takım" },
      { term: "teenager", definition: "ergen, genç" },
      { term: "terrible", definition: "berbat" },
      { term: "the news", definition: "haberler" },
      { term: "unhealthy food", definition: "sağlıksız yiyecek" },
      { term: "useful", definition: "yararlı" },
      { term: "waste", definition: "israf etmek / atık" },
      { term: "worry about sth", definition: "bir şey hakkında endişelenmek" }
    ]
  },
  {
    title: "1E Speaking",
    description: "Entertainment and suggestions",
    terms: [
      { term: "cinema ticket", definition: "sinema bileti" },
      { term: "enjoy", definition: "zevk almak, tadını çıkarmak" },
      { term: "expensive", definition: "pahalı" },
      { term: "fantasy book", definition: "fantastik kitap" },
      { term: "good idea", definition: "iyi fikir" },
      { term: "next week", definition: "gelecek hafta" },
      { term: "present for sb", definition: "biri için hediye" }
    ]
  },
  {
    title: "1F Listening and Vocabulary",
    description: "Relationships and feelings",
    terms: [
      { term: "agree with sb", definition: "biriyle aynı fikirde olmak" },
      { term: "dream about sth", definition: "bir şey hakkında hayal kurmak/rüya görmek" },
      { term: "family member", definition: "aile üyesi" },
      { term: "guilty pleasure", definition: "gizli zevk (suçluluk duyulan zevk)" },
      { term: "laugh at sb/sth", definition: "birine/bir şeye gülmek" },
      { term: "lifestyle", definition: "yaşam tarzı" },
      { term: "tell sb about sth", definition: "birine bir şeyden bahsetmek" },
      { term: "wait for sb", definition: "birini beklemek" }
    ]
  },
  {
    title: "1G Writing",
    description: "Personal profiles",
    terms: [
      { term: "at college", definition: "üniversitede/kolejde" },
      { term: "fashion", definition: "moda" },
      { term: "finish", definition: "bitirmek" },
      { term: "good at sth", definition: "bir şeyde iyi olmak" },
      { term: "personal information", definition: "kişisel bilgiler" },
      { term: "sports training", definition: "spor antrenmanı" }
    ]
  },

  // --- UNIT 2 ---
  {
    title: "2A Grammar and Vocabulary",
    description: "The House and Rooms",
    terms: [
      { term: "attic", definition: "çatı katı" },
      { term: "balcony", definition: "balkon" },
      { term: "bathroom", definition: "banyo" },
      { term: "bedroom", definition: "yatak odası" },
      { term: "ceiling", definition: "tavan" },
      { term: "cellar", definition: "kiler, bodrum" },
      { term: "climb up/down", definition: "yukarı/aşağı tırmanmak" },
      { term: "dining room", definition: "yemek odası" },
      { term: "door", definition: "kapı" },
      { term: "drawing", definition: "çizim" },
      { term: "floor", definition: "zemin, kat" },
      { term: "front", definition: "ön" },
      { term: "garage", definition: "garaj" },
      { term: "garden", definition: "bahçe" },
      { term: "hall", definition: "hol, koridor" },
      { term: "high", definition: "yüksek" },
      { term: "horse", definition: "at" },
      { term: "kitchen", definition: "mutfak" },
      { term: "living room", definition: "oturma odası" },
      { term: "music studio", definition: "müzik stüdyosu" },
      { term: "paint", definition: "boyamak" },
      { term: "painting", definition: "tablo, resim" },
      { term: "paradise", definition: "cennet" },
      { term: "roof", definition: "çatı" },
      { term: "speakers", definition: "hoparlörler" },
      { term: "stairs", definition: "merdivenler" },
      { term: "straight", definition: "düz" },
      { term: "study", definition: "çalışma odası" },
      { term: "swimming pool", definition: "yüzme havuzu" },
      { term: "terrace", definition: "teras" },
      { term: "upstairs/downstairs", definition: "üst kat / alt kat" },
      { term: "wall", definition: "duvar" },
      { term: "window", definition: "pencere" }
    ]
  },
  {
    title: "2B Vocabulary",
    description: "Furniture and Household Items",
    terms: [
      { term: "armchair", definition: "koltuk" },
      { term: "attractive", definition: "çekici" },
      { term: "bath", definition: "küvet" },
      { term: "behind", definition: "arkasında" },
      { term: "between", definition: "arasında" },
      { term: "breakfast bar", definition: "kahvaltı barı" },
      { term: "carpet", definition: "halı" },
      { term: "cooker", definition: "ocak" },
      { term: "cupboard", definition: "dolap" },
      { term: "dishwasher", definition: "bulaşık makinesi" },
      { term: "fireplace", definition: "şömine" },
      { term: "for rent", definition: "kiralık" },
      { term: "fridge", definition: "buzdolabı" },
      { term: "furniture", definition: "mobilya" },
      { term: "LED TV", definition: "LED televizyon" },
      { term: "light", definition: "açık (renk) / hafif" },
      { term: "lovely", definition: "sevimli, hoş" },
      { term: "microwave", definition: "mikrodalga" },
      { term: "mirror", definition: "ayna" },
      { term: "next to", definition: "yanında" },
      { term: "opposite", definition: "karşısında" },
      { term: "perfect", definition: "mükemmel" },
      { term: "rug", definition: "kilim" },
      { term: "shelf (pl. shelves)", definition: "raf (raflar)" },
      { term: "shower", definition: "duş" },
      { term: "sink", definition: "lavabo" },
      { term: "sofa", definition: "kanepe" },
      { term: "ten-minute walk from", definition: "...dan on dakikalık yürüme mesafesinde" },
      { term: "toilet", definition: "tuvalet" },
      { term: "view", definition: "manzara" },
      { term: "wardrobe", definition: "gardırop" },
      { term: "washbasin", definition: "lavabo (banyo)" },
      { term: "washing machine", definition: "çamaşır makinesi" }
    ]
  },
  {
    title: "2C Grammar and Vocabulary",
    description: "Chores and Housework",
    terms: [
      { term: "cook a meal", definition: "yemek pişirmek" },
      { term: "do chores", definition: "ev işleri yapmak" },
      { term: "do the washing-up", definition: "bulaşık yıkamak" },
      { term: "keep your room tidy", definition: "odanı düzenli tutmak" },
      { term: "leave home", definition: "evden ayrılmak" },
      { term: "sweep the floor", definition: "yeri süpürmek" },
      { term: "vacuum the carpet", definition: "halıyı süpürmek" },
      { term: "wash/dry/iron clothes", definition: "kıyafetleri yıkamak/kurutmak/ütülemek" }
    ]
  },
  {
    title: "2D Reading and Vocabulary",
    description: "Describing Places",
    terms: [
      { term: "building", definition: "bina" },
      { term: "clean", definition: "temiz" },
      { term: "cold", definition: "soğuk" },
      { term: "comfortable", definition: "rahat" },
      { term: "community", definition: "topluluk" },
      { term: "dangerous", definition: "tehlikeli" },
      { term: "dark", definition: "karanlık" },
      { term: "dirty", definition: "kirli" },
      { term: "empty", definition: "boş" },
      { term: "familiar atmosphere", definition: "tanıdık atmosfer" },
      { term: "fantastic", definition: "harika" },
      { term: "feel homesick", definition: "ev hasreti çekmek" },
      { term: "flat/apartment", definition: "daire" },
      { term: "full of people", definition: "insan dolu" },
      { term: "hot", definition: "sıcak" },
      { term: "light", definition: "aydınlık" },
      { term: "messy", definition: "dağınık" },
      { term: "modern", definition: "modern" },
      { term: "neighbour", definition: "komşu" },
      { term: "noisy", definition: "gürültülü" },
      { term: "normal", definition: "normal" },
      { term: "object", definition: "nesne" },
      { term: "quiet", definition: "sessiz" },
      { term: "special", definition: "özel" },
      { term: "sunny", definition: "güneşli" },
      { term: "terrible", definition: "berbat" },
      { term: "tidy", definition: "düzenli" },
      { term: "top floor", definition: "en üst kat" },
      { term: "traditional", definition: "geleneksel" },
      { term: "traffic", definition: "trafik" },
      { term: "uncomfortable", definition: "rahatsız" }
    ]
  },
  {
    title: "2E Listening and Vocabulary",
    description: "Living with others phrases",
    terms: [
      { term: "do a questionnaire", definition: "anket yapmak/doldurmak" },
      { term: "do your best", definition: "elinden gelenin en iyisini yapmak" },
      { term: "generous", definition: "cömert" },
      { term: "habit", definition: "alışkanlık" },
      { term: "interests", definition: "ilgi alanları" },
      { term: "make a mess", definition: "ortalığı dağıtmak" },
      { term: "make a suggestion", definition: "öneride bulunmak" },
      { term: "make new friends", definition: "yeni arkadaşlar edinmek" },
      { term: "match", definition: "eşleşmek / maç" },
      { term: "roommate", definition: "oda arkadaşı" },
      { term: "share a room", definition: "odayı paylaşmak" }
    ]
  },
  {
    title: "2F Speaking",
    description: "Accommodation phrases",
    terms: [
      { term: "available", definition: "müsait" },
      { term: "location", definition: "konum" },
      { term: "noise", definition: "gürültü" },
      { term: "rent", definition: "kira / kiralamak" },
      { term: "space", definition: "alan, boşluk" }
    ]
  },
  {
    title: "2G Writing",
    description: "Room description words",
    terms: [
      { term: "cover", definition: "kapak / örtmek" },
      { term: "desk", definition: "çalışma masası" },
      { term: "poster", definition: "poster" }
    ]
  },

  // --- UNIT 3 ---
  {
    title: "3A Grammar and Vocabulary",
    description: "Food Types and Groceries",
    terms: [
      { term: "apple", definition: "elma" },
      { term: "banana", definition: "muz" },
      { term: "beef", definition: "sığır eti" },
      { term: "biscuit", definition: "bisküvi" },
      { term: "body weight", definition: "vücut ağırlığı" },
      { term: "bread", definition: "ekmek" },
      { term: "butter", definition: "tereyağı" },
      { term: "cake", definition: "kek, pasta" },
      { term: "calorie", definition: "kalori" },
      { term: "cereal", definition: "mısır gevreği" },
      { term: "cheese", definition: "peynir" },
      { term: "chicken", definition: "tavuk" },
      { term: "chocolate", definition: "çikolata" },
      { term: "coffee", definition: "kahve" },
      { term: "crisps", definition: "cips" },
      { term: "dairy", definition: "süt ürünleri" },
      { term: "dessert", definition: "tatlı" },
      { term: "diet", definition: "diyet" },
      { term: "drink", definition: "içecek / içmek" },
      { term: "eggs", definition: "yumurtalar" },
      { term: "energy drink", definition: "enerji içeceği" },
      { term: "fish", definition: "balık" },
      { term: "fruit", definition: "meyve" },
      { term: "ham", definition: "jambon" },
      { term: "hungry", definition: "aç" },
      { term: "ice cream", definition: "dondurma" },
      { term: "juice", definition: "meyve suyu" },
      { term: "lettuce", definition: "marul" },
      { term: "meat", definition: "et" },
      { term: "milk", definition: "süt" },
      { term: "orange", definition: "portakal" },
      { term: "pasta", definition: "makarna" },
      { term: "pizza", definition: "pizza" },
      { term: "potato", definition: "patates" },
      { term: "rice", definition: "pirinç" },
      { term: "sardines", definition: "sardalya" },
      { term: "snack", definition: "atıştırmalık" },
      { term: "spinach", definition: "ıspanak" },
      { term: "tea", definition: "çay" },
      { term: "sandwich", definition: "sandviç" },
      { term: "tomato", definition: "domates" },
      { term: "tuna", definition: "ton balığı" },
      { term: "vegetables", definition: "sebzeler" },
      { term: "water", definition: "su" },
      { term: "yoghurt", definition: "yoğurt" }
    ]
  },
  {
    title: "3B Vocabulary",
    description: "Food Containers and Quantities",
    terms: [
      { term: "bag", definition: "poşet, çanta" },
      { term: "bottle", definition: "şişe" },
      { term: "box", definition: "kutu" },
      { term: "can", definition: "metal konser kutusu" },
      { term: "carton", definition: "karton kutu" },
      { term: "free", definition: "ücretsiz / özgür" },
      { term: "jar", definition: "kavanoz" },
      { term: "lemonade", definition: "limonata" },
      { term: "mayonnaise", definition: "mayonez" },
      { term: "packet", definition: "paket" },
      { term: "pence", definition: "kuruş (İngiliz para birimi)" },
      { term: "pound", definition: "sterlin" },
      { term: "price", definition: "fiyat" },
      { term: "salad", definition: "salata" },
      { term: "special offer", definition: "özel teklif / kampanya" },
      { term: "sweets", definition: "şekerlemeler" },
      { term: "tin", definition: "teneke kutu" },
      { term: "tomato sauce", definition: "domates sosu" }
    ]
  },
  {
    title: "3C Speaking",
    description: "Ordering Food and Drinks",
    terms: [
      { term: "carrot cake", definition: "havuçlu kek" },
      { term: "change", definition: "para üstü / bozukluk / değiştirmek" },
      { term: "customer", definition: "müşteri" },
      { term: "order", definition: "sipariş vermek / sipariş" },
      { term: "server", definition: "garson" },
      { term: "sparkling/still water", definition: "gazlı/durgun (normal) su" }
    ]
  },
  {
    title: "3D Grammar",
    description: "Food Storage and Waste",
    terms: [
      { term: "chips", definition: "patates kızartması" },
      { term: "food waste", definition: "gıda israfı" },
      { term: "freeze", definition: "dondurmak" },
      { term: "keep", definition: "saklamak / tutmak" },
      { term: "leftovers", definition: "arta kalan yemekler" },
      { term: "shopping list", definition: "alışveriş listesi" },
      { term: "smart", definition: "akıllı / şık" },
      { term: "store", definition: "depolamak / dükkan" },
      { term: "sugar", definition: "şeker" },
      { term: "throw away", definition: "çöpe atmak / atmak" },
      { term: "use-by date", definition: "son kullanma tarihi" }
    ]
  },
  {
    title: "3E Listening and Vocabulary",
    description: "Professions and Kitchen Items",
    terms: [
      { term: "baker", definition: "fırıncı" },
      { term: "bowl", definition: "kase" },
      { term: "butcher", definition: "kasap" },
      { term: "chef", definition: "şef / aşçı" },
      { term: "cup", definition: "fincan" },
      { term: "dietician", definition: "diyetisyen" },
      { term: "equipment", definition: "ekipman" },
      { term: "food photographer", definition: "yemek fotoğrafçısı" },
      { term: "fork", definition: "çatal" },
      { term: "fresh", definition: "taze" },
      { term: "glass", definition: "bardak / cam" },
      { term: "job", definition: "iş / meslek" },
      { term: "knife", definition: "bıçak" },
      { term: "plate", definition: "tabak" },
      { term: "restaurant reviewer", definition: "restoran eleştirmeni" },
      { term: "sell", definition: "satmak" },
      { term: "spoon", definition: "kaşık" },
      { term: "steak", definition: "biftek" },
      { term: "waiter", definition: "garson" }
    ]
  },
  {
    title: "3F Reading and Vocabulary",
    description: "Dining Out and Environment",
    terms: [
      { term: "cheap", definition: "ucuz" },
      { term: "collect", definition: "toplamak" },
      { term: "cost", definition: "mal olmak / maliyet" },
      { term: "delicious", definition: "lezzetli" },
      { term: "dish", definition: "yemek / tabak" },
      { term: "eat in", definition: "evde yemek" },
      { term: "eat out", definition: "dışarıda yemek" },
      { term: "environment", definition: "çevre" },
      { term: "ethical", definition: "etik" },
      { term: "find out", definition: "öğrenmek / bulmak" },
      { term: "give out", definition: "dağıtmak" },
      { term: "give up", definition: "vazgeçmek / bırakmak" },
      { term: "help out", definition: "yardım etmek" },
      { term: "homeless people", definition: "evsiz insanlar" },
      { term: "main course", definition: "ana yemek" },
      { term: "natural/local ingredients", definition: "doğal/yerel malzemeler" },
      { term: "organic", definition: "organik" },
      { term: "pizzeria/pizza restaurant", definition: "pizzacı" },
      { term: "search (by sth)", definition: "(bir şeye göre) aramak" },
      { term: "serve", definition: "servis etmek / hizmet etmek" },
      { term: "sit down", definition: "oturmak" },
      { term: "spend/save money", definition: "para harcamak/biriktirmek" },
      { term: "starter", definition: "başlangıç yemeği" },
      { term: "taste", definition: "tatmak / tat" },
      { term: "vegetarian", definition: "vejetaryen" }
    ]
  },
  {
    title: "3G Writing",
    description: "Restaurant Vocabulary",
    terms: [
      { term: "opening hours", definition: "açılış saatleri" },
      { term: "speciality", definition: "uzmanlık alanı / spesiyalite" }
    ]
  },

  // --- UNIT 4 ---
  {
    title: "4A Grammar and Vocabulary",
    description: "School Places and Activities",
    terms: [
      { term: "afterschool club", definition: "okul sonrası kulübü" },
      { term: "art room", definition: "resim atölyesi" },
      { term: "be late", definition: "geç kalmak" },
      { term: "canteen", definition: "kantin" },
      { term: "check your timetable", definition: "ders programını kontrol etmek" },
      { term: "classroom", definition: "sınıf" },
      { term: "computer room", definition: "bilgisayar odası" },
      { term: "documentary", definition: "belgesel" },
      { term: "gym", definition: "spor salonu" },
      { term: "hallway", definition: "koridor" },
      { term: "hold on", definition: "beklemek (telefonda)" },
      { term: "library", definition: "kütüphane" },
      { term: "make a phone call", definition: "telefon görüşmesi yapmak" },
      { term: "music room", definition: "müzik odası" },
      { term: "playing fields", definition: "oyun sahaları" },
      { term: "prepare", definition: "hazırlamak" },
      { term: "school uniform", definition: "okul üniforması" },
      { term: "science lab", definition: "fen laboratuvarı" },
      { term: "staffroom", definition: "öğretmenler odası" },
      { term: "term", definition: "dönem" }
    ]
  },
  {
    title: "4B Vocabulary",
    description: "School Subjects and Objects",
    terms: [
      { term: "act", definition: "rol yapmak" },
      { term: "Art", definition: "Resim dersi" },
      { term: "atom", definition: "atom" },
      { term: "backpack", definition: "sırt çantası" },
      { term: "Biology", definition: "Biyoloji" },
      { term: "calculator", definition: "hesap makinesi" },
      { term: "Chemistry", definition: "Kimya" },
      { term: "climate", definition: "iklim" },
      { term: "Computer Science", definition: "Bilgisayar Bilimi" },
      { term: "continent", definition: "kıta" },
      { term: "dictionary", definition: "sözlük" },
      { term: "Drama", definition: "Tiyatro/Drama dersi" },
      { term: "education", definition: "eğitim" },
      { term: "electricity", definition: "elektrik" },
      { term: "element", definition: "element" },
      { term: "folder", definition: "dosya" },
      { term: "foreign languages", definition: "yabancı diller" },
      { term: "Geography", definition: "Coğrafya" },
      { term: "headphones", definition: "kulaklık" },
      { term: "highlighter", definition: "fosforlu kalem" },
      { term: "History", definition: "Tarih" },
      { term: "keys", definition: "anahtarlar" },
      { term: "Maths", definition: "Matematik" },
      { term: "Music", definition: "Müzik dersi" },
      { term: "notebook", definition: "defter" },
      { term: "object", definition: "nesne" },
      { term: "Physical Education", definition: "Beden Eğitimi" },
      { term: "Physics", definition: "Fizik" },
      { term: "plant", definition: "bitki" },
      { term: "play an instrument", definition: "enstrüman çalmak" },
      { term: "ruler", definition: "cetvel" },
      { term: "school bag", definition: "okul çantası" },
      { term: "substance", definition: "madde" },
      { term: "textbook", definition: "ders kitabı" },
      { term: "the past", definition: "geçmiş" },
      { term: "tissue", definition: "kağıt mendil" }
    ]
  },
  {
    title: "4C Grammar",
    description: "School Roles and Activities",
    terms: [
      { term: "assistant head teacher", definition: "müdür yardımcısı" },
      { term: "character", definition: "karakter" },
      { term: "computer code", definition: "bilgisayar kodu" },
      { term: "essay", definition: "makale / deneme" },
      { term: "have a debate", definition: "tartışma yapmak" },
      { term: "improve", definition: "geliştirmek" },
      { term: "join", definition: "katılmak" },
      { term: "listening/speaking skills", definition: "dinleme/konuşma becerileri" },
      { term: "meeting", definition: "toplantı" },
      { term: "pen", definition: "tükenmez kalem" },
      { term: "practise doing sth", definition: "bir şeyi yapma alıştırması yapmak" },
      { term: "role", definition: "rol" },
      { term: "take over", definition: "devralmak" },
      { term: "takeover", definition: "devralma" }
    ]
  },
  {
    title: "4D Reading and Vocabulary",
    description: "Education and Projects",
    terms: [
      { term: "adventure", definition: "macera" },
      { term: "arrive at (school)", definition: "(okula) varmak" },
      { term: "assembly", definition: "okul toplanması / meclis" },
      { term: "design a computer game", definition: "bilgisayar oyunu tasarlamak" },
      { term: "do a project", definition: "proje yapmak" },
      { term: "do a subject", definition: "bir dersi almak" },
      { term: "games designer", definition: "oyun tasarımcısı" },
      { term: "gaming", definition: "oyun oynama" },
      { term: "get a qualification", definition: "yeterlilik/diploma kazanmak" },
      { term: "get good grades", definition: "iyi notlar almak" },
      { term: "mix", definition: "karıştırmak" },
      { term: "motivated", definition: "motive olmuş" },
      { term: "office", definition: "ofis" },
      { term: "optional", definition: "seçmeli" },
      { term: "pass/fail an exam", definition: "sınavı geçmek/kalmak" },
      { term: "practical", definition: "uygulamalı / pratik" },
      { term: "smart", definition: "zeki / şık" },
      { term: "take a break", definition: "mola vermek" },
      { term: "take an exam", definition: "sınava girmek" },
      { term: "test", definition: "test / sınav" },
      { term: "working day", definition: "iş günü" }
    ]
  },
  {
    title: "4E Listening and Vocabulary",
    description: "Transport and Travel",
    terms: [
      { term: "advert", definition: "reklam" },
      { term: "by car/bus/public transport", definition: "arabayla/otobüsle/toplu taşımayla" },
      { term: "canal", definition: "kanal" },
      { term: "challenge", definition: "meydan okuma" },
      { term: "closed", definition: "kapalı" },
      { term: "crowded", definition: "kalabalık" },
      { term: "dangerous", definition: "tehlikeli" },
      { term: "expensive", definition: "pahalı" },
      { term: "free", definition: "ücretsiz" },
      { term: "freezing", definition: "dondurucu soğuk" },
      { term: "fun", definition: "eğlence / eğlenceli" },
      { term: "get to school", definition: "okula gitmek" },
      { term: "journey", definition: "yolculuk" },
      { term: "kilometre", definition: "kilometre" },
      { term: "ladder", definition: "seyyar merdiven" },
      { term: "on foot", definition: "yürüyerek" },
      { term: "plane", definition: "uçak" },
      { term: "simple", definition: "basit" },
      { term: "skater", definition: "patenci" },
      { term: "skating/ice-skating", definition: "paten / buz pateni" },
      { term: "take", definition: "almak / (süre) sürmek" },
      { term: "take a flight", definition: "uçağa binmek / uçmak" },
      { term: "tiny", definition: "küçücük" },
      { term: "travel", definition: "seyahat etmek" },
      { term: "village", definition: "köy" },
      { term: "walk", definition: "yürümek" }
    ]
  },
  {
    title: "4F Speaking",
    description: "Requests and Permissions",
    terms: [
      { term: "borrow", definition: "ödünç almak" },
      { term: "go to the toilet", definition: "tuvalete gitmek" },
      { term: "loud", definition: "yüksek sesli" }
    ]
  },
  {
    title: "4G Writing",
    description: "Communication and School",
    terms: [
      { term: "chat with friends", definition: "arkadaşlarla sohbet etmek" },
      { term: "give a talk", definition: "konuşma/sunum yapmak" },
      { term: "Internet forum post", definition: "internet forum gönderisi" },
      { term: "secondary school", definition: "ortaokul/lise" }
    ]
  },

  // --- UNIT 5 ---
  {
    title: "5A Grammar and Vocabulary",
    description: "Feelings and Personality",
    terms: [
      { term: "accident", definition: "kaza" },
      { term: "brave", definition: "cesur" },
      { term: "confident", definition: "kendine güvenen" },
      { term: "creative", definition: "yaratıcı" },
      { term: "cry", definition: "ağlamak" },
      { term: "die", definition: "ölmek" },
      { term: "easy-going", definition: "uyumlu / rahat" },
      { term: "feel afraid/scared", definition: "korkmak" },
      { term: "fire", definition: "ateş / yangın" },
      { term: "firefighter", definition: "itfaiyeci" },
      { term: "funny", definition: "komik / eğlenceli" },
      { term: "helpful", definition: "yardımsever" },
      { term: "hero", definition: "kahraman" },
      { term: "inspire", definition: "ilham vermek" },
      { term: "move house", definition: "ev taşımak" },
      { term: "patient", definition: "sabırlı" },
      { term: "push", definition: "itmek" },
      { term: "reach", definition: "ulaşmak / erişmek" },
      { term: "ride a horse", definition: "ata binmek" },
      { term: "save", definition: "kurtarmak / biriktirmek / kaydetmek" },
      { term: "serious", definition: "ciddi" },
      { term: "shout at sb", definition: "birine bağırmak" }
    ]
  },
  {
    title: "5B Vocabulary",
    description: "Appearance and Clothing",
    terms: [
      { term: "appearance", definition: "dış görünüş" },
      { term: "attractive", definition: "çekici" },
      { term: "bald", definition: "kel" },
      { term: "beard", definition: "sakal" },
      { term: "blue/grey/brown/green eyes", definition: "mavi/gri/kahverengi/yeşil gözler" },
      { term: "boots", definition: "botlar" },
      { term: "build", definition: "vücut yapısı" },
      { term: "cardigan", definition: "hırka" },
      { term: "coat", definition: "palto / kaban" },
      { term: "curly/straight/wavy hair", definition: "kıvırcık/düz/dalgalı saç" },
      { term: "dark/fair/grey/white/blond(e)/red/brown/black hair", definition: "koyu/açık(kumral)/gri/beyaz/sarışın/kızıl/kahverengi/siyah saç" },
      { term: "dress", definition: "elbise" },
      { term: "gloves", definition: "eldiven" },
      { term: "good-looking", definition: "iyi görünümlü (yakışıklı/güzel)" },
      { term: "hair colour/type/length", definition: "saç rengi/tipi/uzunluğu" },
      { term: "hat", definition: "şapka" },
      { term: "height", definition: "boy" },
      { term: "hoody", definition: "kapüşonlu sweatshirt" },
      { term: "jacket", definition: "ceket" },
      { term: "jeans", definition: "kot pantolon" },
      { term: "jumper", definition: "kazak" },
      { term: "middle-aged", definition: "orta yaşlı" },
      { term: "nice", definition: "hoş / güzel" },
      { term: "old", definition: "yaşlı / eski" },
      { term: "pretty", definition: "sevimli / güzel" },
      { term: "scarf", definition: "atkı / eşarp" },
      { term: "shirt", definition: "gömlek" },
      { term: "shoes", definition: "ayakkabı" },
      { term: "short/medium-length/long hair", definition: "kısa/orta uzunlukta/uzun saç" },
      { term: "skirt", definition: "etek" },
      { term: "slim", definition: "ince / zayıf" },
      { term: "smile", definition: "gülümseme" },
      { term: "socks", definition: "çorap" },
      { term: "tall", definition: "uzun" },
      { term: "thin", definition: "zayıf" },
      { term: "top", definition: "üst (kıyafet)" },
      { term: "tracksuit bottoms", definition: "eşofman altı" },
      { term: "trainers", definition: "spor ayakkabı" },
      { term: "trousers", definition: "pantolon" },
      { term: "T-shirt", definition: "tişört" },
      { term: "well-built", definition: "yapılı (vücut)" },
      { term: "young", definition: "genç" }
    ]
  },
  {
    title: "5C Speaking",
    description: "Shopping for Clothes",
    terms: [
      { term: "changing room", definition: "deneme kabini" },
      { term: "fit", definition: "uymak (beden olarak)" },
      { term: "go shopping for clothes", definition: "kıyafet alışverişine gitmek" },
      { term: "sales assistant", definition: "satış görevlisi" },
      { term: "size", definition: "beden / numara" },
      { term: "small/medium/large", definition: "küçük(S)/orta(M)/büyük(L)" },
      { term: "suit", definition: "yakışmak (stil olarak)" },
      { term: "try on", definition: "denemek (kıyafet)" }
    ]
  },
  {
    title: "5D Grammar",
    description: "Fashion and Trends",
    terms: [
      { term: "dress", definition: "giyinmek" },
      { term: "go bald", definition: "kelleşmek" },
      { term: "platform shoes", definition: "platform ayakkabılar" },
      { term: "unfashionable", definition: "modası geçmiş / rüküş" },
      { term: "wear make-up", definition: "makyaj yapmak" }
    ]
  },
  {
    title: "5E Listening and Vocabulary",
    description: "Gender and Stereotypes",
    terms: [
      { term: "campaign", definition: "kampanya" },
      { term: "century", definition: "yüzyıl" },
      { term: "construction", definition: "inşaat" },
      { term: "fit", definition: "uymak / uygun olmak" },
      { term: "gender", definition: "cinsiyet" },
      { term: "go with sth", definition: "bir şeyle uyumlu olmak / gitmek" },
      { term: "good quality", definition: "iyi kalite" },
      { term: "match", definition: "eşleşmek / uymak" },
      { term: "stereotyping", definition: "kalıplaştırma / etiketleme" },
      { term: "suit", definition: "uymak / yakışmak" },
      { term: "toy", definition: "oyuncak" },
      { term: "western world", definition: "batı dünyası" }
    ]
  },
  {
    title: "5F Reading and Vocabulary",
    description: "Lookalikes and Doppelgängers",
    terms: [
      { term: "combine", definition: "birleştirmek" },
      { term: "contact", definition: "iletişim kurmak" },
      { term: "current photo", definition: "güncel fotoğraf" },
      { term: "difference", definition: "fark" },
      { term: "different from", definition: "...dan farklı" },
      { term: "doppelgänger", definition: "tıpatıp benzer (ikiz gibi)" },
      { term: "digital", definition: "dijital" },
      { term: "double", definition: "çift / benzeri" },
      { term: "facial features", definition: "yüz hatları" },
      { term: "feel an instant connection", definition: "anında bağ hissetmek" },
      { term: "find a match", definition: "bir eşleşme bulmak" },
      { term: "genes", definition: "genler" },
      { term: "have a lot in common", definition: "çok fazla ortak noktası olmak" },
      { term: "have a point", definition: "haklılık payı olmak" },
      { term: "identical", definition: "özdeş / aynı" },
      { term: "look like sb", definition: "birine benzemek" },
      { term: "look/seem different", definition: "farklı görünmek" },
      { term: "lookalike", definition: "benzer kişi" },
      { term: "looks", definition: "görünüş" },
      { term: "meet face to face", definition: "yüz yüze tanışmak/görüşmek" },
      { term: "qualities", definition: "nitelikler / özellikler" },
      { term: "shape", definition: "şekil" },
      { term: "shy", definition: "utangaç" },
      { term: "similar to sb", definition: "birine benzer" },
      { term: "sound", definition: "ses / gibi gelmek" },
      { term: "specific", definition: "belirli / özgül" },
      { term: "tell jokes", definition: "fıkra anlatmak / şaka yapmak" },
      { term: "the same (as sb/sth)", definition: "aynı (birisiyle/bir şeyle)" },
      { term: "twin", definition: "ikiz" },
      { term: "virtual", definition: "sanal" }
    ]
  },
  {
    title: "5G Writing",
    description: "Describing People",
    terms: [
      { term: "fancy doing sth", definition: "bir şey yapmayı istemek / canı çekmek" },
      { term: "primary school", definition: "ilkokul" }
    ]
  },

  // --- UNIT 6 ---
  {
    title: "6A Grammar and Vocabulary",
    description: "Art, Movies, and Literature",
    terms: [
      { term: "3D printing", definition: "3D baskı" },
      { term: "actor/actress", definition: "erkek oyuncu / kadın oyuncu" },
      { term: "art gallery", definition: "sanat galerisi" },
      { term: "choreographer", definition: "koreograf" },
      { term: "composer", definition: "besteci" },
      { term: "copy", definition: "kopya / kopyalamak" },
      { term: "create", definition: "yaratmak / oluşturmak" },
      { term: "creator", definition: "yaratıcı" },
      { term: "dance", definition: "dans" },
      { term: "dancer", definition: "dansçı" },
      { term: "director", definition: "yönetmen" },
      { term: "fast", definition: "hızlı" },
      { term: "film", definition: "film" },
      { term: "literature", definition: "edebiyat" },
      { term: "movie", definition: "film (sinema)" },
      { term: "museum", definition: "müze" },
      { term: "music", definition: "müzik" },
      { term: "musician", definition: "müzisyen" },
      { term: "painter", definition: "ressam" },
      { term: "painting", definition: "tablo / resim" },
      { term: "photographer", definition: "fotoğrafçı" },
      { term: "photography", definition: "fotoğrafçılık" },
      { term: "piece of music/literature", definition: "müzik/edebiyat eseri" },
      { term: "poet", definition: "şair" },
      { term: "rap", definition: "rap yapmak" },
      { term: "record", definition: "kayıt / plak" },
      { term: "record-breaking", definition: "rekor kıran" },
      { term: "sales", definition: "satışlar" },
      { term: "scriptwriter", definition: "senarist" },
      { term: "sculptor", definition: "heykeltıraş" },
      { term: "sculpture", definition: "heykel" },
      { term: "seat", definition: "koltuk" },
      { term: "stage", definition: "sahne" },
      { term: "talented", definition: "yetenekli" },
      { term: "theatre", definition: "tiyatro" },
      { term: "trailer", definition: "fragman" },
      { term: "version", definition: "versiyon / sürüm" },
      { term: "visitor", definition: "ziyaretçi" },
      { term: "world record", definition: "dünya rekoru" },
      { term: "writer", definition: "yazar" }
    ]
  },
  {
    title: "6B Reading and Vocabulary",
    description: "Festivals and Events",
    terms: [
      { term: "annual", definition: "yıllık" },
      { term: "attract", definition: "cezbetmek / çekmek" },
      { term: "awesome", definition: "harika / müthiş" },
      { term: "awful", definition: "berbat" },
      { term: "boring", definition: "sıkıcı" },
      { term: "brief", definition: "kısa / öz" },
      { term: "brilliant", definition: "muhteşem / parlak" },
      { term: "clean up", definition: "temizlemek" },
      { term: "delicious", definition: "lezzetli" },
      { term: "disgusting", definition: "iğrenç" },
      { term: "earn", definition: "kazanmak (para)" },
      { term: "guide to sth", definition: "bir şeyin rehberi" },
      { term: "headliner", definition: "baş sanatçı (festivalde)" },
      { term: "live show", definition: "canlı gösteri" },
      { term: "luxurious", definition: "lüks" },
      { term: "music/arts festival", definition: "müzik/sanat festivali" },
      { term: "performer", definition: "sanatçı / icracı" },
      { term: "population", definition: "nüfus" },
      { term: "sell out", definition: "yok satmak / tükenmek" },
      { term: "show up", definition: "ortaya çıkmak / gelmek" },
      { term: "star", definition: "yıldız" },
      { term: "talented", definition: "yetenekli" },
      { term: "tent", definition: "çadır" },
      { term: "volunteer", definition: "gönüllü" },
      { term: "weather forecast", definition: "hava durumu tahmini" },
      { term: "wellies", definition: "lastik çizmeler" },
      { term: "wet", definition: "ıslak" }
    ]
  },
  {
    title: "6C Vocabulary",
    description: "Film Genres and Features",
    terms: [
      { term: "action film", definition: "aksiyon filmi" },
      { term: "animated film", definition: "animasyon filmi" },
      { term: "audience", definition: "seyirci / izleyici kitlesi" },
      { term: "big-/low-budget", definition: "büyük/düşük bütçeli" },
      { term: "cast", definition: "oyuncu kadrosu" },
      { term: "character", definition: "karakter" },
      { term: "comedy", definition: "komedi" },
      { term: "computer-generated images", definition: "bilgisayar üretimi görüntüler (CGI)" },
      { term: "disappointing", definition: "hayal kırıklığı yaratan" },
      { term: "documentary", definition: "belgesel" },
      { term: "drama", definition: "drama" },
      { term: "ending", definition: "son / bitiş" },
      { term: "exciting", definition: "heyecan verici" },
      { term: "fantasy film", definition: "fantastik film" },
      { term: "funny", definition: "komik" },
      { term: "horror film", definition: "korku filmi" },
      { term: "main character", definition: "ana karakter" },
      { term: "musical", definition: "müzikal" },
      { term: "original", definition: "orijinal / özgün" },
      { term: "plot", definition: "olay örgüsü / konu" },
      { term: "predictable", definition: "tahmin edilebilir" },
      { term: "romance", definition: "romantik film / aşk" },
      { term: "scary", definition: "korkutucu" },
      { term: "scene", definition: "sahne" },
      { term: "science fiction film", definition: "bilim kurgu filmi" },
      { term: "soundtrack", definition: "film müziği" },
      { term: "special effects", definition: "özel efektler" },
      { term: "superhero film", definition: "süper kahraman filmi" },
      { term: "unusual", definition: "olağandışı" },
      { term: "western", definition: "kovboy filmi" }
    ]
  },
  {
    title: "6D Grammar",
    description: "Performance Verbs",
    terms: [
      { term: "camera", definition: "kamera" },
      { term: "direct", definition: "yönetmek" },
      { term: "perform", definition: "sahnelemek / performans sergilemek" },
      { term: "school play", definition: "okul piyesi/oyunu" },
      { term: "screen", definition: "ekran / perde" }
    ]
  },
  {
    title: "6E Listening and Vocabulary",
    description: "Phrases with 'Get' and Art",
    terms: [
      { term: "be unsuccessful", definition: "başarısız olmak" },
      { term: "get a call", definition: "bir arama almak" },
      { term: "get a fine", definition: "ceza yemek (para cezası)" },
      { term: "get a good grade", definition: "iyi not almak" },
      { term: "get bored/angry", definition: "sıkılmak / sinirlenmek" },
      { term: "get dark", definition: "hava kararmak" },
      { term: "get home/to school", definition: "eve/okula varmak" },
      { term: "get worse", definition: "kötüleşmek" },
      { term: "graffiti artist", definition: "grafiti sanatçısı" },
      { term: "mask", definition: "maske" },
      { term: "modern art", definition: "modern sanat" },
      { term: "spray paint", definition: "sprey boya" },
      { term: "street art", definition: "sokak sanatı" },
      { term: "tagging", definition: "tag yapma (imza atma)" }
    ]
  },
  {
    title: "6F Speaking",
    description: "Leisure Activities",
    terms: [
      { term: "check your diary", definition: "ajandanı kontrol etmek" },
      { term: "go to an exhibition", definition: "bir sergiye gitmek" },
      { term: "watch a series", definition: "dizi izlemek" }
    ]
  },
  {
    title: "6G Writing",
    description: "Film Review Terms",
    terms: [
      { term: "acting", definition: "oyunculuk" },
      { term: "be set in ...", definition: "...'da geçmek (yer/zaman)" },
      { term: "beginning", definition: "başlangıç" },
      { term: "incredible", definition: "inanılmaz" },
      { term: "recommend", definition: "tavsiye etmek" },
      { term: "win an Oscar", definition: "Oscar kazanmak" }
    ]
  },

  // --- UNIT 7 ---
  {
    title: "7A Grammar and Vocabulary",
    description: "Holidays and Travel Activities",
    terms: [
      { term: "at the seaside", definition: "deniz kenarında" },
      { term: "book a ticket", definition: "bilet ayırtmak" },
      { term: "do (some) sightseeing", definition: "gezi yapmak / etrafı gezmek" },
      { term: "get a summer job", definition: "yaz işi bulmak" },
      { term: "go away", definition: "bir yere gitmek / tatile çıkmak" },
      { term: "go to an open-air theatre/a lido/a party/the cinema/the beach/the park", definition: "açık hava tiyatrosuna/havuza/partiye/sinemaya/plaja/parka gitmek" },
      { term: "have a picnic/a barbecue/a party", definition: "piknik/mangal/parti yapmak" },
      { term: "have a takeaway", definition: "paket yemek yemek" },
      { term: "have coffee/a meal", definition: "kahve içmek / yemek yemek" },
      { term: "have plans", definition: "planları olmak" },
      { term: "look out for sb", definition: "birini kollamak / dikkat etmek" },
      { term: "stay with sb", definition: "birinde kalmak" },
      { term: "take a trip", definition: "geziye çıkmak" },
      { term: "travel around Europe", definition: "Avrupa'yı gezmek" },
      { term: "visit a museum/a city", definition: "müzeyi/şehri ziyaret etmek" },
      { term: "visit family/friends", definition: "aileyi/arkadaşları ziyaret etmek" },
      { term: "watch a match/a show/a band", definition: "maç/gösteri/grup izlemek" }
    ]
  },
  {
    title: "7B Vocabulary",
    description: "City Places and Transport",
    terms: [
      { term: "airport", definition: "havalimanı" },
      { term: "art gallery", definition: "sanat galerisi" },
      { term: "bank", definition: "banka" },
      { term: "bridge", definition: "köprü" },
      { term: "bus service", definition: "otobüs seferi" },
      { term: "canal", definition: "kanal" },
      { term: "car park", definition: "otopark (isim) / park etmek (fiil)" },
      { term: "castle", definition: "kale" },
      { term: "church", definition: "kilise" },
      { term: "cinema", definition: "sinema" },
      { term: "concert hall", definition: "konser salonu" },
      { term: "drive (your car)", definition: "(araba) sürmek" },
      { term: "driver", definition: "şoför" },
      { term: "get on/off the bus", definition: "otobüse binmek/inmek" },
      { term: "go back", definition: "geri dönmek" },
      { term: "go by boat/plane", definition: "tekneyle/uçakla gitmek" },
      { term: "go by train/coach/bus/tram", definition: "trenle/şehirlerarası otobüsle/otobüsle/tramvayla gitmek" },
      { term: "go on foot", definition: "yürüyerek gitmek" },
      { term: "hospital", definition: "hastane" },
      { term: "hotel", definition: "otel" },
      { term: "library", definition: "kütüphane" },
      { term: "market", definition: "pazar / market" },
      { term: "motorway", definition: "otoyol" },
      { term: "museum", definition: "müze" },
      { term: "on board", definition: "araçta / gemide" },
      { term: "park", definition: "park" },
      { term: "post office", definition: "postane" },
      { term: "quay", definition: "rıhtım" },
      { term: "restaurant", definition: "restoran" },
      { term: "ride a bike/a moped/a motorbike", definition: "bisiklet/moped/motosiklet sürmek" },
      { term: "see an exhibition", definition: "sergi görmek" },
      { term: "shopping centre", definition: "alışveriş merkezi" },
      { term: "sports centre", definition: "spor merkezi" },
      { term: "square", definition: "meydan" },
      { term: "station", definition: "istasyon" },
      { term: "supermarket", definition: "süpermarket" },
      { term: "take a taxi/a bus/a tram", definition: "taksi/otobüs/tramvay tutmak(kullanmak)" },
      { term: "take a water taxi/a boat", definition: "deniz taksi/tekne tutmak" },
      { term: "theatre", definition: "tiyatro" },
      { term: "tourist information centre", definition: "turist danışma merkezi" },
      { term: "town hall", definition: "belediye binası" },
      { term: "train/bus station", definition: "tren/otobüs istasyonu" },
      { term: "travelcard", definition: "seyahat kartı" },
      { term: "walk", definition: "yürümek" }
    ]
  },
  {
    title: "7C Listening",
    description: "Travel Announcements and Stations",
    terms: [
      { term: "attention", definition: "dikkat" },
      { term: "belongings", definition: "eşyalar" },
      { term: "block", definition: "engellemek" },
      { term: "board a train", definition: "trene binmek" },
      { term: "exit", definition: "çıkış" },
      { term: "gift", definition: "hediye" },
      { term: "give sb a warning", definition: "birine uyarı vermek" },
      { term: "interval", definition: "ara (tiyatro vb.)" },
      { term: "make an announcement", definition: "duyuru yapmak" },
      { term: "member of staff", definition: "personel üyesi" },
      { term: "passenger", definition: "yolcu" },
      { term: "performance", definition: "performans" },
      { term: "play", definition: "oyun (sahne)" },
      { term: "selection (of books)", definition: "kitap seçkisi" },
      { term: "station staff", definition: "istasyon personeli" },
      { term: "ticket office", definition: "bilet gişesi" },
      { term: "underground station", definition: "metro istasyonu" },
      { term: "underground train", definition: "metro treni" }
    ]
  },
  {
    title: "7D Grammar",
    description: "Travel Types",
    terms: [
      { term: "aerial tram", definition: "teleferik" },
      { term: "art tour", definition: "sanat turu" },
      { term: "fly", definition: "uçmak" },
      { term: "hotel reception", definition: "otel resepsiyonu" },
      { term: "island", definition: "ada" },
      { term: "tour guide", definition: "tur rehberi" },
      { term: "tourist sight", definition: "turistik yer" }
    ]
  },
  {
    title: "7E Speaking",
    description: "Asking for Directions",
    terms: [
      { term: "ask for/give directions", definition: "yol sormak/tarif etmek" },
      { term: "road", definition: "yol" },
      { term: "tell sb the way", definition: "birine yolu tarif etmek" }
    ]
  },
  {
    title: "7F Reading and Vocabulary",
    description: "Travel Experiences",
    terms: [
      { term: "admire", definition: "hayran olmak / seyretmek" },
      { term: "architecture", definition: "mimari" },
      { term: "book a place (on a flight)", definition: "yer ayırtmak (uçakta)" },
      { term: "buy a ticket", definition: "bilet almak" },
      { term: "check the train timetable", definition: "tren tarifesini kontrol etmek" },
      { term: "create a profile", definition: "profil oluşturmak" },
      { term: "cultural site", definition: "kültürel alan" },
      { term: "find accommodation", definition: "konaklama bulmak" },
      { term: "go on your own", definition: "tek başına gitmek" },
      { term: "hire a bike", definition: "bisiklet kiralamak" },
      { term: "hostel", definition: "pansiyon / hostel" },
      { term: "keep costs low", definition: "masrafları düşük tutmak" },
      { term: "on Earth", definition: "Dünya üzerinde" },
      { term: "opera house", definition: "opera binası" },
      { term: "prison", definition: "hapishane" },
      { term: "rich", definition: "zengin" },
      { term: "snorkel", definition: "şnorkelle yüzmek" },
      { term: "space", definition: "uzay / boşluk" },
      { term: "stay with a host family", definition: "ev sahibi ailenin yanında kalmak" },
      { term: "take a tour of the city", definition: "şehir turuna çıkmak" },
      { term: "travel cheaply", definition: "ucuza seyahat etmek" },
      { term: "work of art", definition: "sanat eseri" }
    ]
  },
  {
    title: "7G Writing",
    description: "Correspondence",
    terms: [
      { term: "letter", definition: "mektup" },
      { term: "on time", definition: "zamanında" },
      { term: "parents’ evening", definition: "veli toplantısı" },
      { term: "social media message", definition: "sosyal medya mesajı" },
      { term: "text message", definition: "kısa mesaj (SMS)" }
    ]
  },

  // --- UNIT 8 ---
  {
    title: "8A Grammar and Vocabulary",
    description: "Future Technology and Gadgets",
    terms: [
      { term: "3D printer", definition: "3D yazıcı" },
      { term: "analyse", definition: "analiz etmek" },
      { term: "automatically", definition: "otomatik olarak" },
      { term: "charger", definition: "şarj aleti" },
      { term: "checkout", definition: "kasa / ödeme noktası" },
      { term: "coin", definition: "madeni para" },
      { term: "deliver", definition: "teslim etmek" },
      { term: "drone", definition: "dron" },
      { term: "electric car", definition: "elektrikli araba" },
      { term: "future", definition: "gelecek" },
      { term: "gadget", definition: "alet / edevat" },
      { term: "health tracker", definition: "sağlık takip cihazı" },
      { term: "make contact with sb", definition: "biriyle iletişim kurmak" },
      { term: "Moon", definition: "Ay" },
      { term: "note", definition: "kağıt para / not" },
      { term: "part of the body", definition: "vücut bölümü" },
      { term: "petrol car", definition: "benzinli araba" },
      { term: "planet", definition: "gezegen" },
      { term: "robot", definition: "robot" },
      { term: "scientist", definition: "bilim insanı" },
      { term: "smartphone", definition: "akıllı telefon" },
      { term: "smartwatch", definition: "akıllı saat" },
      { term: "tablet computer", definition: "tablet bilgisayar" },
      { term: "virtual reality (VR) headset", definition: "sanal gerçeklik (VR) başlığı" },
      { term: "wireless headphones", definition: "kablosuz kulaklık" }
    ]
  },
  {
    title: "8B Vocabulary",
    description: "Computer Actions and Hardware",
    terms: [
      { term: "attach a cable", definition: "kablo takmak/bağlamak" },
      { term: "attach a file", definition: "dosya eklemek" },
      { term: "charge", definition: "şarj etmek" },
      { term: "computer equipment", definition: "bilgisayar ekipmanı" },
      { term: "copy some text/a file", definition: "metin/dosya kopyalamak" },
      { term: "delete a file/an email", definition: "dosya/e-posta silmek" },
      { term: "desktop computer", definition: "masaüstü bilgisayar" },
      { term: "download music/an app", definition: "müzik/uygulama indirmek" },
      { term: "hard disk", definition: "sabit disk" },
      { term: "install an app/a printer", definition: "uygulama/yazıcı yüklemek" },
      { term: "laptop battery", definition: "dizüstü bilgisayar bataryası" },
      { term: "PC", definition: "kişisel bilgisayar" },
      { term: "print", definition: "yazdırmak" },
      { term: "save a document", definition: "belge kaydetmek" },
      { term: "scan", definition: "taramak" },
      { term: "scanner", definition: "tarayıcı" },
      { term: "screen", definition: "ekran" },
      { term: "speakers", definition: "hoparlörler" },
      { term: "switch off", definition: "kapatmak" },
      { term: "tech-free", definition: "teknolojisiz" },
      { term: "turn up", definition: "sesini açmak / ortaya çıkmak" },
      { term: "type", definition: "yazmak (klavyede)" },
      { term: "USB cable", definition: "USB kablosu" },
      { term: "wireless keyboard/mouse", definition: "kablosuz klavye/fare" }
    ]
  },
  {
    title: "8C Grammar",
    description: "Adverbs of Manner",
    terms: [
      { term: "badly", definition: "kötü bir şekilde" },
      { term: "confidently", definition: "kendinden emin bir şekilde" },
      { term: "dangerously", definition: "tehlikeli bir şekilde" },
      { term: "do well in an exam", definition: "sınavda iyi yapmak" },
      { term: "fast", definition: "hızlı" },
      { term: "happily", definition: "mutlu bir şekilde" },
      { term: "hard", definition: "sıkı / zor" },
      { term: "healthily", definition: "sağlıklı bir şekilde" },
      { term: "key ring", definition: "anahtarlık" },
      { term: "lose", definition: "kaybetmek" },
      { term: "loudly", definition: "yüksek sesle" },
      { term: "perfectly", definition: "mükemmel bir şekilde" },
      { term: "politely", definition: "kibarca" },
      { term: "press a button", definition: "düğmeye basmak" },
      { term: "safely", definition: "güvenli bir şekilde" },
      { term: "slowly", definition: "yavaşça" },
      { term: "start up", definition: "başlatmak / çalışmak" },
      { term: "tracker", definition: "takip cihazı" },
      { term: "urgently", definition: "acilen" },
      { term: "well", definition: "iyi" }
    ]
  },
  {
    title: "8D Listening and Vocabulary",
    description: "Inventions and Discovery",
    terms: [
      { term: "broken", definition: "kırık / bozuk" },
      { term: "develop", definition: "geliştirmek" },
      { term: "discover", definition: "keşfetmek" },
      { term: "excited", definition: "heyecanlı" },
      { term: "experiment with sth", definition: "bir şeyle deney yapmak" },
      { term: "frightened", definition: "korkmuş" },
      { term: "invent", definition: "icat etmek" },
      { term: "produce", definition: "üretmek" },
      { term: "surprised", definition: "şaşırmış" },
      { term: "test", definition: "test etmek" },
      { term: "time machine", definition: "zaman makinesi" },
      { term: "time travel", definition: "zaman yolculuğu" },
      { term: "travel in time", definition: "zamanda yolculuk etmek" }
    ]
  },
  {
    title: "8E Speaking",
    description: "Smart Technology",
    terms: [
      { term: "alive", definition: "canlı / hayatta" },
      { term: "imagine", definition: "hayal etmek" },
      { term: "Internet access", definition: "internet erişimi" },
      { term: "make life easier", definition: "hayatı kolaylaştırmak" },
      { term: "personal robot", definition: "kişisel robot" },
      { term: "start an app", definition: "uygulama başlatmak" },
      { term: "turn the lights on/off", definition: "ışıkları açmak/kapatmak" },
      { term: "voice assistant", definition: "sesli asistan" }
    ]
  },
  {
    title: "8F Reading and Vocabulary",
    description: "Emotions and AI",
    terms: [
      { term: "amazed", definition: "hayran kalmış / şaşırmış" },
      { term: "angry", definition: "kızgın" },
      { term: "bored", definition: "sıkılmış" },
      { term: "breathing", definition: "nefes alma" },
      { term: "communicate face-to-face", definition: "yüz yüze iletişim kurmak" },
      { term: "communicate online", definition: "çevrimiçi iletişim kurmak" },
      { term: "computer scientist", definition: "bilgisayar bilimcisi" },
      { term: "excited", definition: "heyecanlı" },
      { term: "happy", definition: "mutlu" },
      { term: "heart", definition: "kalp" },
      { term: "human brain", definition: "insan beyni" },
      { term: "in a good/bad mood", definition: "iyi/kötü ruh halinde" },
      { term: "interaction", definition: "etkileşim" },
      { term: "recognise", definition: "tanımak" },
      { term: "researcher", definition: "araştırmacı" },
      { term: "sad", definition: "üzgün" },
      { term: "scared", definition: "korkmuş" },
      { term: "software", definition: "yazılım" },
      { term: "solve problems", definition: "problemleri çözmek" },
      { term: "stressed", definition: "stresli" },
      { term: "surprised", definition: "şaşırmış" },
      { term: "understand/recognise/show emotions", definition: "duyguları anlamak/tanımak/göstermek" },
      { term: "worried", definition: "endişeli" }
    ]
  },
  {
    title: "8G Writing",
    description: "Gadgets and Descriptions",
    terms: [
      { term: "fitness tracker", definition: "fitness takipçisi" },
      { term: "in perfect condition", definition: "mükemmel durumda" },
      { term: "notice", definition: "fark etmek / duyuru" },
      { term: "possession", definition: "sahip olunan şey / eşya" },
      { term: "reward", definition: "ödül" },
      { term: "swap", definition: "takas etmek" }
    ]
  },

  // --- UNIT 9 ---
  {
    title: "9A Grammar and Vocabulary",
    description: "Sports and Activities",
    terms: [
      { term: "aerobics", definition: "aerobik" },
      { term: "athletics", definition: "atletizm" },
      { term: "basketball", definition: "basketbol" },
      { term: "climbing", definition: "tırmanış" },
      { term: "competitive", definition: "rekabetçi" },
      { term: "cycling", definition: "bisiklet sürme" },
      { term: "defend", definition: "savunmak" },
      { term: "goalkeeper", definition: "kaleci" },
      { term: "gymnastics", definition: "jimnastik" },
      { term: "hit the ball", definition: "topa vurmak" },
      { term: "hockey", definition: "hokey" },
      { term: "horse riding", definition: "ata binme" },
      { term: "hurt yourself", definition: "kendini incitmek" },
      { term: "judo", definition: "judo" },
      { term: "karate", definition: "karate" },
      { term: "kayaker", definition: "kano sporcusu" },
      { term: "kayaking", definition: "kano" },
      { term: "mountain biking", definition: "dağ bisikleti" },
      { term: "rugby", definition: "ragbi" },
      { term: "skateboarding", definition: "kaykay" },
      { term: "snow", definition: "kar" },
      { term: "swimming", definition: "yüzme" },
      { term: "tennis", definition: "tenis" },
      { term: "underwater", definition: "su altı" },
      { term: "volleyball", definition: "voleybol" },
      { term: "win", definition: "kazanmak" },
      { term: "yoga", definition: "yoga" }
    ]
  },
  {
    title: "9B Listening and Vocabulary",
    description: "Sports Equipment and Events",
    terms: [
      { term: "alarm clock", definition: "çalar saat" },
      { term: "baseball/cricket bat", definition: "beyzbol/kriket sopası" },
      { term: "cyclist", definition: "bisikletçi" },
      { term: "field", definition: "saha / alan" },
      { term: "FIFA World Cup", definition: "FIFA Dünya Kupası" },
      { term: "football goal", definition: "futbol kalesi" },
      { term: "football team", definition: "futbol takımı" },
      { term: "footballer", definition: "futbolcu" },
      { term: "gloves", definition: "eldiven" },
      { term: "goalkeeper", definition: "kaleci" },
      { term: "helmet", definition: "kask" },
      { term: "life jacket", definition: "can yeleği" },
      { term: "swimming goggles", definition: "yüzme gözlüğü" },
      { term: "table tennis bat", definition: "masa tenisi raketi" },
      { term: "tennis/badminton racket", definition: "tenis/badminton raketi" },
      { term: "tennis net", definition: "tenis filesi" },
      { term: "towel", definition: "havlu" },
      { term: "trophy", definition: "kupa / ödül" }
    ]
  },
  {
    title: "9C Vocabulary",
    description: "The Body",
    terms: [
      { term: "ankle", definition: "ayak bileği" },
      { term: "arm", definition: "kol" },
      { term: "back", definition: "sırt" },
      { term: "body", definition: "vücut" },
      { term: "ear", definition: "kulak" },
      { term: "elbow", definition: "dirsek" },
      { term: "eye", definition: "göz" },
      { term: "face", definition: "yüz" },
      { term: "fat", definition: "şişman" },
      { term: "flat", definition: "düz" },
      { term: "finger", definition: "parmak" },
      { term: "foot (pl. feet)", definition: "ayak (ayaklar)" },
      { term: "hand", definition: "el" },
      { term: "hard", definition: "sert" },
      { term: "head", definition: "baş / kafa" },
      { term: "knee", definition: "diz" },
      { term: "leg", definition: "bacak" },
      { term: "mouth", definition: "ağız" },
      { term: "narrow", definition: "dar" },
      { term: "neck", definition: "boyun" },
      { term: "nose", definition: "burun" },
      { term: "round", definition: "yuvarlak" },
      { term: "shoulder", definition: "omuz" },
      { term: "slim", definition: "ince / zayıf" },
      { term: "soft", definition: "yumuşak" },
      { term: "stomach", definition: "mide / karın" },
      { term: "strong", definition: "güçlü" },
      { term: "toe", definition: "ayak parmağı" },
      { term: "tooth (pl. teeth)", definition: "diş (dişler)" },
      { term: "weak", definition: "güçsüz / zayıf" },
      { term: "wide", definition: "geniş" },
      { term: "wrist", definition: "el bileği" }
    ]
  },
  {
    title: "9D Grammar and Vocabulary",
    description: "Health and Illness",
    terms: [
      { term: "feel sick", definition: "hasta hissetmek / midesi bulanmak" },
      { term: "go to the dentist", definition: "dişçiye gitmek" },
      { term: "have a headache/toothache/backache/stomach ache/earache", definition: "baş/diş/sırt/karın/kulak ağrısı çekmek" },
      { term: "have a sore throat", definition: "boğazı ağrımak" },
      { term: "have a temperature", definition: "ateşi olmak" },
      { term: "hurt", definition: "acımak / incitmek" },
      { term: "see a doctor", definition: "doktora görünmek" },
      { term: "take some aspirin", definition: "aspirin almak" }
    ]
  },
  {
    title: "9E Speaking",
    description: "Describing Symptoms",
    terms: [
      { term: "feel alright", definition: "iyi hissetmek" },
      { term: "feel weak", definition: "halsiz hissetmek" },
      { term: "have a cold", definition: "nezle olmak / üşütmek" },
      { term: "illness", definition: "hastalık" },
      { term: "symptom", definition: "belirti" }
    ]
  },
  {
    title: "9F Reading and Vocabulary",
    description: "Space and Survival",
    terms: [
      { term: "astronaut", definition: "astronot" },
      { term: "blood", definition: "kan" },
      { term: "bone", definition: "kemik" },
      { term: "candidate", definition: "aday" },
      { term: "dry food", definition: "kuru gıda" },
      { term: "extreme conditions", definition: "aşırı koşullar" },
      { term: "grow", definition: "büyümek / yetiştirmek" },
      { term: "health problems", definition: "sağlık sorunları" },
      { term: "heart", definition: "kalp" },
      { term: "International Space Station", definition: "Uluslararası Uzay İstasyonu" },
      { term: "liquid", definition: "sıvı" },
      { term: "mind", definition: "zihin" },
      { term: "muscle", definition: "kas" },
      { term: "organ", definition: "organ" },
      { term: "pilot", definition: "pilot" },
      { term: "protect something from", definition: "bir şeyi ...dan korumak" },
      { term: "running water", definition: "akan su / şebeke suyu" },
      { term: "skin", definition: "deri / cilt" },
      { term: "space suit", definition: "uzay giysisi" },
      { term: "space travel", definition: "uzay yolculuğu" },
      { term: "survive", definition: "hayatta kalmak" },
      { term: "train to be (an astronaut)", definition: "(astronot) olmak için eğitim almak" },
      { term: "zero gravity", definition: "yerçekimsizlik" }
    ]
  },
  {
    title: "9G Writing",
    description: "Health Habits",
    terms: [
      { term: "bad diet", definition: "kötü beslenme" },
      { term: "fizzy drink", definition: "gazlı içecek" },
      { term: "fresh air", definition: "temiz hava" },
      { term: "stress", definition: "stres" },
      { term: "sugary snacks", definition: "şekerli atıştırmalıklar" }
    ]
  },

  // --- UNIT 10 ---
  {
    title: "10A Grammar and Vocabulary",
    description: "Nature and Geography",
    terms: [
      { term: "abroad", definition: "yurt dışı" },
      { term: "beach", definition: "plaj / kumsal" },
      { term: "coast", definition: "sahil / kıyı" },
      { term: "desert", definition: "çöl" },
      { term: "elephant", definition: "fil" },
      { term: "forest", definition: "orman" },
      { term: "hill", definition: "tepe" },
      { term: "island", definition: "ada" },
      { term: "jungle", definition: "balta girmemiş orman" },
      { term: "lake", definition: "göl" },
      { term: "mountain", definition: "dağ" },
      { term: "ocean", definition: "okyanus" },
      { term: "open water", definition: "açık deniz / su" },
      { term: "river", definition: "nehir" },
      { term: "rocks", definition: "kayalar" },
      { term: "sand", definition: "kum" },
      { term: "sea", definition: "deniz" },
      { term: "valley", definition: "vadi" },
      { term: "waterfall", definition: "şelale" }
    ]
  },
  {
    title: "10B Vocabulary",
    description: "Animals and Insects",
    terms: [
      { term: "ant", definition: "karınca" },
      { term: "beak", definition: "gaga" },
      { term: "bee", definition: "arı" },
      { term: "bird", definition: "kuş" },
      { term: "body part", definition: "vücut bölümü" },
      { term: "crocodile", definition: "timsah" },
      { term: "dolphin", definition: "yunus" },
      { term: "duck", definition: "ördek" },
      { term: "feather", definition: "tüy" },
      { term: "fish", definition: "balık" },
      { term: "fly", definition: "sinek" },
      { term: "fur", definition: "kürk / post" },
      { term: "honey", definition: "bal" },
      { term: "insect", definition: "böcek" },
      { term: "lion", definition: "aslan" },
      { term: "mammal", definition: "memeli" },
      { term: "monkey", definition: "maymun" },
      { term: "mosquito", definition: "sivrisinek" },
      { term: "penguin", definition: "penguen" },
      { term: "reptile", definition: "sürüngen" },
      { term: "salmon", definition: "somon" },
      { term: "shark", definition: "köpekbalığı" },
      { term: "sharp", definition: "keskin" },
      { term: "skin", definition: "deri" },
      { term: "snake", definition: "yılan" },
      { term: "tail", definition: "kuyruk" },
      { term: "thick", definition: "kalın" },
      { term: "tiger", definition: "kaplan" },
      { term: "tooth (pl. teeth)", definition: "diş (dişler)" },
      { term: "whale", definition: "balina" },
      { term: "wings", definition: "kanatlar" }
    ]
  },
  {
    title: "10C Grammar",
    description: "Environment and Volunteering",
    terms: [
      { term: "do a survey", definition: "anket yapmak" },
      { term: "do volunteer work", definition: "gönüllü çalışmak" },
      { term: "environmental", definition: "çevresel" },
      { term: "plastic bag", definition: "plastik poşet" },
      { term: "post a comment/a photo/a question", definition: "yorum/fotoğraf/soru göndermek/paylaşmak" },
      { term: "recycling", definition: "geri dönüşüm" }
    ]
  },
  {
    title: "10D Reading and Vocabulary",
    description: "Pollution and Conservation",
    terms: [
      { term: "ban", definition: "yasaklamak" },
      { term: "bottled water", definition: "şişe su" },
      { term: "campaign", definition: "kampanya" },
      { term: "decompose", definition: "çürümek / ayrışmak" },
      { term: "kill", definition: "öldürmek" },
      { term: "local government", definition: "yerel yönetim" },
      { term: "plastic packaging", definition: "plastik ambalaj" },
      { term: "plastic pollution", definition: "plastik kirliliği" },
      { term: "plastic/glass bottle", definition: "plastik/cam şişe" },
      { term: "present", definition: "sunmak" },
      { term: "promise", definition: "söz vermek" },
      { term: "recycle", definition: "geri dönüştürmek" },
      { term: "reduce waste", definition: "atığı azaltmak" },
      { term: "research", definition: "araştırma" },
      { term: "sign a petition", definition: "dilekçe/imza kampanyası imzalamak" },
      { term: "signature", definition: "imza" },
      { term: "spread", definition: "yayılmak" },
      { term: "supporter", definition: "destekçi" },
      { term: "tourism", definition: "turizm" },
      { term: "wet season", definition: "yağışlı mevsim" },
      { term: "wildlife", definition: "vahşi yaşam" },
      { term: "wind", definition: "rüzgar" },
      { term: "world leader", definition: "dünya lideri" }
    ]
  },
  {
    title: "10E Listening and Vocabulary",
    description: "Weather and Seasons",
    terms: [
      { term: "advise", definition: "tavsiye vermek" },
      { term: "appropriate", definition: "uygun" },
      { term: "bad weather", definition: "kötü hava" },
      { term: "cloud", definition: "bulut" },
      { term: "cloudy", definition: "bulutlu" },
      { term: "degree", definition: "derece" },
      { term: "fall over", definition: "düşmek" },
      { term: "fog", definition: "sis" },
      { term: "foggy", definition: "sisli" },
      { term: "heavy rain", definition: "sağanak yağmur" },
      { term: "lightning", definition: "şimşek / yıldırım" },
      { term: "rainy", definition: "yağmurlu" },
      { term: "season", definition: "mevsim" },
      { term: "sky", definition: "gökyüzü" },
      { term: "snow", definition: "kar" },
      { term: "snowy", definition: "karlı" },
      { term: "storm", definition: "fırtına" },
      { term: "stormy", definition: "fırtınalı" },
      { term: "sun", definition: "güneş" },
      { term: "sunny", definition: "güneşli" },
      { term: "temperature", definition: "sıcaklık" },
      { term: "topic", definition: "konu" },
      { term: "umbrella", definition: "şemsiye" },
      { term: "weather forecast", definition: "hava durumu tahmini" },
      { term: "wind", definition: "rüzgar" },
      { term: "windy", definition: "rüzgarlı" }
    ]
  },
  {
    title: "10F Speaking",
    description: "Green Initiatives",
    terms: [
      { term: "appear", definition: "görünmek" },
      { term: "design", definition: "tasarlamak" },
      { term: "give a speech", definition: "konuşma yapmak" },
      { term: "go green", definition: "çevreci olmak / yeşillenmek" },
      { term: "good news", definition: "iyi haber" },
      { term: "passion for sth", definition: "bir şeye tutku duymak" }
    ]
  },
  {
    title: "10G Writing and Vocabulary",
    description: "Environmental Problems",
    terms: [
      { term: "air pollution", definition: "hava kirliliği" },
      { term: "attract", definition: "çekmek / cezbetmek" },
      { term: "grow food", definition: "yiyecek yetiştirmek" },
      { term: "rat", definition: "sıçan / fare" },
      { term: "rubbish bin", definition: "çöp kutusu" },
      { term: "set an example", definition: "örnek olmak" },
      { term: "spread diseases", definition: "hastalık yaymak" },
      { term: "traffic pollution", definition: "trafik kirliliği" },
      { term: "win a prize", definition: "ödül kazanmak" }
    ]
  }
];
